name: dependencies

on:
  pull_request:
    paths:
    - pyproject.toml
    - requirements*

# Only allow one instance of this workflow for each PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: python -m pip install uv
    - run: uv pip compile --universal --output-file=requirements.txt requirements.in pyproject.toml
    - run: git diff --exit-code
