name: dependencies

on:
  pull_request:
    paths:
    - requirements*

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: python -m pip install pip-tools
    - run: pip-compile --output-file=requirements.txt requirements.in setup.cfg
    - run: git diff --exit-code
